import { ArrowLeft, Check, ChevronRight, CircleStop, ExternalLink, GitBranch, History, Play, Plus, RefreshCw, RotateCcw, Server, ShieldCheck, TriangleAlert, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { api, ApiError, type Agent, type Deployment, type DeploymentPreview, type Role, type RuntimeProject } from './api'
import type { Locale, Page } from './App'

const copy = {
  en: {
    title: 'Reviewed Git deployments', description: 'Deploy a public GitHub revision only after both policy boundaries approve its normalized Compose model.', new: 'New deployment', source: 'Source', target: 'Target', review: 'Policy review', confirm: 'Confirm', repository: 'Public GitHub repository', commit: 'Fixed 40-character commit SHA', path: 'Compose path', next: 'Continue', back: 'Back', agent: 'Agent', name: 'Display name', project: 'Stable project name', preview: 'Validate source', services: 'Services', images: 'Images', warnings: 'Warnings', noWarnings: 'No policy warnings', create: 'Create immutable revision', catalog: 'Deployment catalog', empty: 'No reviewed deployments yet.', deploy: 'Approve & deploy', newRevision: 'Deploy new revision', stop: 'Stop', rollback: 'Rollback', runtime: 'Runtime', logs: 'Logs', domain: 'Publish domain', current: 'Current revision', run: 'Latest run', commitLabel: 'Source commit', loading: 'Loading deployments', ownerOnly: 'Only the Owner can create, approve, stop, or roll back deployments. Runtime-only controls remain available to Operators on discovered services.', failed: 'The deployment request could not be completed.', invalid: 'Check the source and target fields.', protected: 'Protected projects cannot be deployed.', digest: 'Digest pinned', tagged: 'Version tag', health: 'Healthcheck', missingHealth: 'Healthcheck recommended', injected: 'Safe resource defaults injected', imageWarning: 'Digest pinning recommended', close: 'Close', chooseRollback: 'Choose an older revision', status: 'Status', revisionCreated: 'The immutable revision was created. Deployment still requires explicit approval.', queued: 'The deployment run was queued.', noAgents: 'Enroll and enable an Agent before creating a deployment.', sourceNote: 'GatewayControl constructs the raw GitHub URL internally. Redirects, credentials, arbitrary hosts, traversal, and files over 1 MiB are rejected.', noYaml: 'Raw Compose and environment values are never displayed or returned to this page.', step: 'Step', of: 'of', cancel: 'Cancel', refresh: 'Refresh',
  },
  ar: {
    title: 'عمليات نشر Git المراجعة', description: 'انشر مراجعة عامة من GitHub فقط بعد موافقة سياستي مخدم التحكم والعميل على نموذج Compose الموحّد.', new: 'عملية نشر جديدة', source: 'المصدر', target: 'الوجهة', review: 'مراجعة السياسة', confirm: 'التأكيد', repository: 'مستودع GitHub عام', commit: 'معرّف Commit ثابت من 40 محرفاً', path: 'مسار Compose', next: 'متابعة', back: 'رجوع', agent: 'العميل', name: 'الاسم المعروض', project: 'اسم المشروع الثابت', preview: 'التحقق من المصدر', services: 'الخدمات', images: 'الصور', warnings: 'التحذيرات', noWarnings: 'لا توجد تحذيرات من السياسة', create: 'إنشاء مراجعة غير قابلة للتعديل', catalog: 'دليل عمليات النشر', empty: 'لا توجد عمليات نشر مراجعة بعد.', deploy: 'الموافقة والنشر', newRevision: 'نشر مراجعة جديدة', stop: 'إيقاف', rollback: 'رجوع لمراجعة سابقة', runtime: 'التشغيل', logs: 'السجلات', domain: 'نشر نطاق', current: 'المراجعة الحالية', run: 'آخر عملية', commitLabel: 'Commit المصدر', loading: 'جارٍ تحميل عمليات النشر', ownerOnly: 'يمكن للمالك فقط الإنشاء والموافقة والإيقاف والرجوع. تبقى إجراءات التشغيل للخدمات المكتشفة متاحة للمشغّل.', failed: 'تعذر إكمال طلب النشر.', invalid: 'تحقق من حقول المصدر والوجهة.', protected: 'لا يمكن نشر المشاريع المحمية.', digest: 'مثبتة بالبصمة', tagged: 'إصدار محدد', health: 'فحص صحة', missingHealth: 'يوصى بفحص صحة', injected: 'أضيفت حدود موارد آمنة', imageWarning: 'يوصى بتثبيت بصمة الصورة', close: 'إغلاق', chooseRollback: 'اختر مراجعة أقدم', status: 'الحالة', revisionCreated: 'أُنشئت المراجعة غير القابلة للتعديل، وما زال النشر يتطلب موافقة صريحة.', queued: 'أُدرجت عملية النشر في قائمة الانتظار.', noAgents: 'سجّل عميلاً وفعّله قبل إنشاء عملية نشر.', sourceNote: 'ينشئ GatewayControl رابط GitHub الخام داخلياً ويرفض إعادة التوجيه وبيانات الدخول والمضيفات الاعتباطية والتنقل وملفات أكبر من 1 MiB.', noYaml: 'لا تُعرض إعدادات Compose الخام أو قيم البيئة ولا تعاد إلى هذه الصفحة.', step: 'الخطوة', of: 'من', cancel: 'إلغاء', refresh: 'تحديث',
  },
} as const

const panel = 'rounded-[1.4rem] border border-stone-200/80 bg-sand-50 shadow-panel dark:border-white/[0.07] dark:bg-ink-900/80'
const input = 'h-12 w-full rounded-xl border border-stone-200 bg-white px-3.5 text-sm font-semibold text-ink-800 outline-none transition focus:border-mint-400 focus:ring-4 focus:ring-mint-400/10 dark:border-white/[0.08] dark:bg-white/[0.035] dark:text-stone-100'
const button = 'flex min-h-11 items-center justify-center gap-2 rounded-xl border border-stone-200 bg-white px-4 text-xs font-extrabold transition hover:border-mint-400 disabled:cursor-not-allowed disabled:opacity-50 dark:border-white/10 dark:bg-white/5'
const primary = 'flex min-h-11 items-center justify-center gap-2 rounded-xl bg-ink-900 px-5 text-xs font-extrabold text-white disabled:cursor-not-allowed disabled:opacity-50 dark:bg-mint-400 dark:text-ink-950'

export function DeploymentsPage({ locale, role, navigate }: { locale: Locale; role: Role; navigate: (page: Page) => void }) {
  const t = copy[locale]
  const [deployments, setDeployments] = useState<Deployment[]>([])
  const [agents, setAgents] = useState<Agent[]>([])
  const [runtimeProjects, setRuntimeProjects] = useState<RuntimeProject[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')
  const [wizard, setWizard] = useState<{ deployment?: Deployment; step: 1 | 2 | 3 | 4 } | null>(null)
  const [repository, setRepository] = useState('https://github.com/')
  const [commitSha, setCommitSha] = useState('')
  const [composePath, setComposePath] = useState('compose.yaml')
  const [agentId, setAgentId] = useState('')
  const [displayName, setDisplayName] = useState('')
  const [projectName, setProjectName] = useState('')
  const [preview, setPreview] = useState<DeploymentPreview | null>(null)
  const [busy, setBusy] = useState(false)
  const [rollback, setRollback] = useState<Deployment | null>(null)

  async function load() {
    setError('')
    try { const [deploymentResult, agentResult, runtimeResult] = await Promise.all([api.deployments(), api.agents(), api.runtimeProjects()]); setDeployments(deploymentResult.deployments); setAgents(agentResult.agents); setRuntimeProjects(runtimeResult.projects); setAgentId((current) => current || agentResult.agents.find((agent) => agent.enabled && agent.enrolledAt)?.id || '') }
    catch { setError(t.failed) } finally { setLoading(false) }
  }
  useEffect(() => { void load() }, [])
  useEffect(() => { if (!deployments.some((item) => ['deploying', 'stopping'].includes(item.status) || ['pending', 'running'].includes(item.latestRun?.status ?? ''))) return; const timer = window.setInterval(() => void load(), 4_000); return () => window.clearInterval(timer) }, [deployments])

  function openWizard(deployment?: Deployment) {
    setWizard({ deployment, step: 1 }); setPreview(null); setError(''); setSuccess(''); setRepository(deployment?.sourceRepository ?? 'https://github.com/'); setCommitSha(''); setComposePath(deployment?.revisions[0]?.composePath ?? 'compose.yaml'); setAgentId(deployment?.agentId ?? agents.find((agent) => agent.enabled && agent.enrolledAt)?.id ?? ''); setDisplayName(deployment?.displayName ?? ''); setProjectName(deployment?.projectName ?? '')
  }
  async function review() {
    if (!repository || commitSha.length !== 40 || !composePath || !agentId || !displayName || !projectName) { setError(t.invalid); return }
    setBusy(true); setError('')
    try { const result = await api.previewDeployment({ repository, commitSha, composePath, projectName }); setPreview(result); setWizard((current) => current ? { ...current, step: 3 } : current) }
    catch (caught) { setError(caught instanceof ApiError && caught.code === 'project_protected' ? t.protected : caught instanceof ApiError ? caught.message : t.failed) } finally { setBusy(false) }
  }
  async function save() {
    if (!wizard || !preview) return
    setBusy(true); setError('')
    try {
      if (wizard.deployment) await api.createDeploymentRevision(wizard.deployment.id, { repository, commitSha, composePath })
      else await api.createDeployment({ repository, commitSha, composePath, projectName, agentId, displayName })
      setSuccess(t.revisionCreated); setWizard(null); await load()
    } catch (caught) { setError(caught instanceof ApiError ? caught.message : t.failed) } finally { setBusy(false) }
  }
  async function run(deployment: Deployment, action: 'deploy' | 'stop' | 'rollback', revisionId?: string) {
    setBusy(true); setError(''); setSuccess('')
    try { if (action === 'deploy') await api.deployRevision(deployment.id, revisionId ?? deployment.revisions[0]!.id); else if (action === 'stop') await api.stopDeployment(deployment.id); else await api.rollbackDeployment(deployment.id, revisionId!); setRollback(null); setSuccess(t.queued); await load() }
    catch (caught) { setError(caught instanceof ApiError ? caught.message : t.failed) } finally { setBusy(false) }
  }
  const availableAgents = agents.filter((agent) => agent.enabled && agent.enrolledAt)
  const steps = [t.source, t.target, t.review, t.confirm]
  return <div className="mx-auto flex w-full max-w-[108rem] flex-col gap-6">
    <header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div className="max-w-3xl"><span className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[0.14em] text-mint-500 dark:text-mint-300"><GitBranch size={15} />GatewayControl</span><h1 className="pt-2 text-3xl font-black tracking-[-0.045em] text-ink-900 dark:text-white sm:text-4xl">{t.title}</h1><p className="pt-2 text-sm font-medium leading-6 text-stone-500 dark:text-stone-400 sm:text-base">{t.description}</p></div><div className="flex flex-col gap-2 sm:flex-row"><button type="button" className={button} onClick={() => void load()}><RefreshCw size={15} />{t.refresh}</button>{role === 'owner' && availableAgents.length > 0 && <button type="button" className={primary} onClick={() => openWizard()}><Plus size={16} />{t.new}</button>}</div></header>
    {role !== 'owner' && <Notice>{t.ownerOnly}</Notice>}{role === 'owner' && availableAgents.length === 0 && !loading && <Notice>{t.noAgents}</Notice>}{error && <Alert>{error}</Alert>}{success && <Success>{success}</Success>}
    {wizard && <section role="dialog" aria-modal="true" className={`${panel} overflow-hidden`}><div className="border-b border-stone-200/80 bg-ink-900 p-5 text-white dark:border-white/[0.07] sm:p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold text-mint-300">{t.step} {wizard.step} {t.of} 4</p><h2 className="pt-1 text-xl font-black">{steps[wizard.step - 1]}</h2></div><button type="button" aria-label={t.close} onClick={() => setWizard(null)} className="rounded-xl p-2 hover:bg-white/10"><X size={19} /></button></div><div className="grid grid-cols-4 gap-2 pt-5">{steps.map((label, index) => <div key={label} className={`h-1.5 rounded-full ${index < wizard.step ? 'bg-mint-400' : 'bg-white/10'}`} />)}</div></div>
      <div className="p-5 sm:p-7">{wizard.step === 1 && <div className="grid grid-cols-1 gap-5 lg:grid-cols-2"><Field label={t.repository}><input autoFocus required dir="ltr" type="url" value={repository} onChange={(event) => setRepository(event.target.value)} className={`${input} text-left font-mono`} /></Field><Field label={t.commit}><input required dir="ltr" minLength={40} maxLength={40} pattern="[0-9a-fA-F]{40}" value={commitSha} onChange={(event) => setCommitSha(event.target.value.trim())} className={`${input} text-left font-mono`} /></Field><div className="lg:col-span-2"><Field label={t.path}><input required dir="ltr" value={composePath} onChange={(event) => setComposePath(event.target.value)} className={`${input} text-left font-mono`} /></Field></div><div className="lg:col-span-2"><Notice>{t.sourceNote}</Notice></div></div>}
        {wizard.step === 2 && <div className="grid grid-cols-1 gap-5 md:grid-cols-3"><Field label={t.agent}><select disabled={Boolean(wizard.deployment)} required value={agentId} onChange={(event) => setAgentId(event.target.value)} className={input}>{availableAgents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></Field><Field label={t.name}><input disabled={Boolean(wizard.deployment)} required maxLength={120} value={displayName} onChange={(event) => setDisplayName(event.target.value)} className={input} /></Field><Field label={t.project}><input disabled={Boolean(wizard.deployment)} required dir="ltr" pattern="[a-z0-9][a-z0-9_-]{0,62}" value={projectName} onChange={(event) => setProjectName(event.target.value)} className={`${input} text-left font-mono`} /></Field></div>}
        {wizard.step === 3 && preview && <PolicyReview preview={preview} locale={locale} />}{wizard.step === 4 && preview && <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><Summary label={t.commitLabel} value={preview.source.commitSha.slice(0, 12)} mono /><Summary label={t.services} value={String(preview.policy.services.length)} /><Summary label={t.warnings} value={String(preview.policy.warnings.length)} /><div className="lg:col-span-3"><Notice>{t.noYaml}</Notice></div></div>}
        <div className="flex flex-col-reverse gap-2 pt-7 sm:flex-row sm:justify-end"><button type="button" className={button} onClick={() => wizard.step === 1 ? setWizard(null) : setWizard({ ...wizard, step: (wizard.step - 1) as 1 | 2 | 3 })}><ArrowLeft className="rtl:rotate-180" size={15} />{wizard.step === 1 ? t.cancel : t.back}</button>{wizard.step < 2 && <button type="button" className={primary} onClick={() => setWizard({ ...wizard, step: 2 })}>{t.next}<ChevronRight className="rtl:rotate-180" size={15} /></button>}{wizard.step === 2 && <button disabled={busy} type="button" className={primary} onClick={() => void review()}><ShieldCheck size={15} />{t.preview}</button>}{wizard.step === 3 && <button type="button" className={primary} onClick={() => setWizard({ ...wizard, step: 4 })}>{t.next}<ChevronRight className="rtl:rotate-180" size={15} /></button>}{wizard.step === 4 && <button disabled={busy} type="button" className={primary} onClick={() => void save()}><Check size={15} />{t.create}</button>}</div>
      </div></section>}
    <section><h2 className="px-1 text-sm font-black text-ink-900 dark:text-white">{t.catalog}</h2><div className="grid grid-cols-1 gap-4 pt-4 xl:grid-cols-2">{deployments.map((deployment) => { const current = deployment.revisions.find((revision) => revision.id === deployment.currentRevisionId); const latest = deployment.revisions[0]; const running = ['pending', 'running'].includes(deployment.latestRun?.status ?? ''); return <article key={deployment.id} className={`${panel} min-w-0 overflow-hidden`}><div className="flex flex-col gap-5 p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><h3 className="truncate text-lg font-black text-ink-900 dark:text-white">{deployment.displayName}</h3><bdi dir="ltr" className="block break-all pt-1 text-left font-mono text-xs text-stone-400">{deployment.projectName}</bdi></div><Status value={deployment.status} /></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><Summary label={t.commitLabel} value={(current ?? latest)?.commitSha.slice(0, 12) ?? '-'} mono /><Summary label={t.current} value={current ? current.checksum.slice(0, 12) : '-'} mono /><Summary label={t.run} value={deployment.latestRun?.status ?? '-'} /></div><div className="flex items-center gap-2 text-xs font-bold text-stone-400"><Server size={14} />{agents.find((agent) => agent.id === deployment.agentId)?.name ?? deployment.agentId}</div>{role === 'owner' && <div className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap"><button disabled={busy || running} type="button" className={button} onClick={() => void run(deployment, 'deploy', latest?.id)}><Play size={14} />{t.deploy}</button><button disabled={busy || running} type="button" className={button} onClick={() => openWizard(deployment)}><GitBranch size={14} />{t.newRevision}</button><button disabled={busy || running || !deployment.currentRevisionId || deployment.status === 'stopped'} type="button" className={button} onClick={() => void run(deployment, 'stop')}><CircleStop size={14} />{t.stop}</button><button disabled={busy || running || deployment.revisions.filter((revision) => revision.id !== deployment.currentRevisionId).length === 0} type="button" className={button} onClick={() => setRollback(deployment)}><RotateCcw size={14} />{t.rollback}</button></div>}</div><div className="grid grid-cols-3 border-t border-stone-200/80 dark:border-white/[0.07]"><LinkButton label={t.runtime} onClick={() => navigate('stacks')} /><LinkButton label={t.logs} onClick={() => navigate('logs')} /><LinkButton label={t.domain} onClick={() => navigate('cloudflareManagement')} /></div></article> })}</div>{loading && <div className={`${panel} mt-4 flex items-center justify-center gap-2 p-8 text-sm font-bold text-stone-400`}><RefreshCw className="animate-spin" size={17} />{t.loading}</div>}{!loading && deployments.length === 0 && <div className={`${panel} mt-4 p-10 text-center text-sm font-bold text-stone-400`}>{t.empty}</div>}</section>
    {rollback && <section role="alertdialog" aria-modal="true" className={`${panel} fixed inset-x-4 bottom-4 z-50 mx-auto max-w-xl p-5 shadow-2xl sm:bottom-8 sm:p-6`}><h2 className="flex items-center gap-2 font-black text-ink-900 dark:text-white"><History size={18} />{t.chooseRollback}</h2><div className="flex max-h-64 flex-col gap-2 overflow-y-auto pt-4">{rollback.revisions.filter((revision) => revision.id !== rollback.currentRevisionId).map((revision) => <button key={revision.id} disabled={busy} type="button" onClick={() => void run(rollback, 'rollback', revision.id)} className={`${button} justify-between text-start`}><bdi dir="ltr" className="font-mono">{revision.commitSha.slice(0, 12)}</bdi><span>{new Date(revision.createdAt).toLocaleDateString(locale)}</span></button>)}</div><button type="button" className={`${button} mt-4 w-full`} onClick={() => setRollback(null)}>{t.cancel}</button></section>}
    <RuntimeMatches deployments={deployments} projects={runtimeProjects} locale={locale} />
  </div>
}

function PolicyReview({ preview, locale }: { preview: DeploymentPreview; locale: Locale }) { const t = copy[locale]; return <div className="grid grid-cols-1 gap-4 xl:grid-cols-[1.5fr_1fr]"><div className={`${panel} overflow-hidden`}><div className="border-b border-stone-200/80 px-4 py-3 text-xs font-black dark:border-white/[0.07]">{t.services}</div><div className="divide-y divide-stone-200/70 dark:divide-white/[0.06]">{preview.policy.services.map((service) => <div key={service.name} className="grid grid-cols-1 gap-2 p-4 sm:grid-cols-[1fr_1.5fr_auto]"><bdi dir="ltr" className="break-all text-left font-mono text-xs font-black">{service.name}</bdi><bdi dir="ltr" className="break-all text-left font-mono text-xs text-stone-500">{service.image}</bdi><div className="flex flex-wrap gap-2"><Badge good={service.digestPinned}>{service.digestPinned ? t.digest : t.tagged}</Badge><Badge good={service.healthcheck}>{service.healthcheck ? t.health : t.missingHealth}</Badge></div></div>)}</div></div><div className={`${panel} p-4`}><h3 className="text-xs font-black">{t.warnings}</h3><div className="flex flex-col gap-2 pt-3">{preview.policy.warnings.length === 0 ? <Badge good>{t.noWarnings}</Badge> : preview.policy.warnings.map((warning, index) => <div key={`${warning.code}-${index}`} className="rounded-xl bg-amber-500/10 p-3 text-xs font-bold text-amber-800 dark:text-amber-200">{warning.service && <bdi dir="ltr" className="me-2 font-mono">{warning.service}</bdi>}{warning.code === 'resource_defaults_injected' ? t.injected : warning.code === 'image_digest_recommended' ? t.imageWarning : t.missingHealth}</div>)}</div></div></div> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="flex min-w-0 flex-col gap-2"><span className="text-xs font-extrabold">{label}</span>{children}</label> }
function Summary({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="min-w-0 rounded-xl bg-stone-100/70 p-3 dark:bg-white/[0.035]"><span className="block text-[0.62rem] font-bold text-stone-400">{label}</span><bdi dir={mono ? 'ltr' : undefined} className={`block truncate pt-1 text-xs font-extrabold ${mono ? 'text-left font-mono' : ''}`}>{value}</bdi></div> }
function Badge({ good, children }: { good: boolean; children: React.ReactNode }) { return <span className={`rounded-full px-2 py-1 text-[0.6rem] font-extrabold ${good ? 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300' : 'bg-amber-500/10 text-amber-700 dark:text-amber-300'}`}>{children}</span> }
function Status({ value }: { value: Deployment['status'] }) { const active = value === 'active'; const failed = value === 'failed'; const arabic: Record<Deployment['status'], string> = { pending: 'قيد الانتظار', deploying: 'جارٍ النشر', active: 'فعّال', stopping: 'جارٍ الإيقاف', stopped: 'متوقف', failed: 'فشل' }; const label = document.documentElement.dir === 'rtl' ? arabic[value] : value; return <span className={`shrink-0 rounded-full px-2.5 py-1 text-[0.65rem] font-extrabold ${active ? 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300' : failed ? 'bg-rose-500/10 text-rose-700 dark:text-rose-300' : 'bg-amber-500/10 text-amber-700 dark:text-amber-300'}`}>{label}</span> }
function LinkButton({ label, onClick }: { label: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="flex min-h-12 items-center justify-center gap-1 border-e border-stone-200/80 px-2 text-xs font-extrabold text-mint-700 last:border-0 dark:border-white/[0.07] dark:text-mint-300">{label}<ExternalLink size={12} /></button> }
function Notice({ children }: { children: React.ReactNode }) { return <div className="rounded-xl bg-amber-500/10 px-3.5 py-3 text-xs font-bold leading-5 text-amber-800 dark:text-amber-200">{children}</div> }
function Alert({ children }: { children: React.ReactNode }) { return <div role="alert" className="flex items-start gap-2 rounded-xl bg-rose-500/10 px-3.5 py-3 text-xs font-bold text-rose-700 dark:text-rose-300"><TriangleAlert className="shrink-0" size={15} />{children}</div> }
function Success({ children }: { children: React.ReactNode }) { return <div role="status" className="flex items-center gap-2 rounded-xl bg-emerald-500/10 px-3.5 py-3 text-xs font-bold text-emerald-700 dark:text-emerald-300"><Check size={15} />{children}</div> }
function RuntimeMatches({ deployments, projects, locale }: { deployments: Deployment[]; projects: RuntimeProject[]; locale: Locale }) { const matched = projects.filter((project) => deployments.some((deployment) => deployment.agentId === project.agentId && deployment.projectName === project.projectName)); if (matched.length === 0) return null; return <section className={`${panel} p-5 sm:p-6`}><h2 className="text-sm font-black text-ink-900 dark:text-white">{copy[locale].services}</h2><div className="grid grid-cols-1 gap-3 pt-4 md:grid-cols-2">{matched.map((project) => <article key={`${project.agentId}:${project.projectName}`} className="rounded-xl bg-stone-100/70 p-4 dark:bg-white/[0.035]"><bdi dir="ltr" className="block break-all text-left font-mono text-xs font-black">{project.projectName}</bdi><div className="flex flex-wrap gap-2 pt-3">{project.services.map((service) => <span key={service.name} className="rounded-full bg-white px-2.5 py-1 font-mono text-[0.65rem] font-bold dark:bg-white/[0.06]"><bdi dir="ltr">{service.name}</bdi> · {service.status}</span>)}</div></article>)}</div></section> }
